"""This notebook shows the current state of the newt re-identification models on our dataset."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_newt_current.ipynb.

# %% auto 0
__all__ = ['BarhillNewtsDataset']

# %% ../nbs/03_newt_current.ipynb 2
import os
import sys
import torch

# %% ../nbs/03_newt_current.ipynb 5
import pandas as pd
from wildlife_datasets import datasets

class BarhillNewtsDataset(datasets.WildlifeDataset):
    @classmethod
    def _download(cls, dataset_name, download_path):
        if not os.path.exists(download_path):
            os.makedirs(download_path, exist_ok=True)
            import kaggle
            kaggle.api.dataset_download_files(dataset_name, path=download_path, unzip=True)
            print(f"Dataset downloaded to {download_path}")
        else:
            print(f"Dataset already exists at {download_path}")

    def create_catalogue(self) -> pd.DataFrame:
        df = pd.read_csv(os.path.join(self.root, "metadata.csv"))
        return df.rename(columns={"newt_id": "identity", "image_id": "image_name", "image_path": "path"})
